#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ImageTest.Resource", IsApplication=true)]

namespace ImageTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cat_error = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cat_loading = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int image_1 = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int image_10 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int image_11 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int image_12 = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int image_2 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int image_3 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int image_4 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int image_5 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int image_6 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int image_7 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int image_8 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int image_9 = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
